services:
  nvim:
    build:
      context: .
      args:
        DISTRO: ${DISTRO} # arch or ubuntu possible
    image: nvim-${DISTRO}:latest
    container_name: nvim-${DISTRO}
    tty: true
    stdin_open: true
    restart: "no"

